version: "3.7"

services:
  workspace:
    build: ./workspace/build
    hostname: workspace
    ports:
      - "127.0.0.1:10022:22"
    volumes:
      - workspace:/home
      - ./workspace:/mnt/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  proxy:
    build: ./proxy/build
    init: true
    hostname: proxy
    ports:
      - "127.0.0.1:3128:3128"
    volumes:
      - ./proxy/squid/squid.conf:/etc/squid/squid.conf
      - ./proxy/squid/conf.local.d:/etc/squid/conf.local.d
    restart: always

volumes:
  workspace:
